<?php
echo '<link rel="stylesheet" href="css/main_gall.css">';
echo Maket::divclasstr('cd-hero',$Pth);
echo Maket::divclasstr('cd-hero-slider',$Pth,'','','ul');
echo Maket::divclasstr('selected',$Pth,'','','li');
echo Maket::divclasstr('cd-full-width',$Pth);
echo Maket::divclasstr('container-fluid js-tm-page-content',$Pth,'','','div data-page-no="1" data-page-type="gallery"' );
echo Maket::divclasstr('tm-img-gallery-container',$Pth);
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-01-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-01.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-02-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-02.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-03-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-03.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-04-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-04.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-05-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-05.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-06-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-06.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-07-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-07.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-08-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-08.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-09-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-09.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-10-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-10.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-11-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-11.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-12-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-12.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-13-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-13.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-14-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-14.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-15-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-15.jpg">View more</a>';
echo '</figcaption></figure></div>';
echo Maket::divclasstr('grid-item',$Pth);
echo Maket::divclasstr('effect-sadie',$Pth,'','','figure');
echo '<img src="img/tm-img-16-tn.jpg" alt="Image" class="img-fluid tm-img">';
echo Maket::divclasstr('',$Pth,'','','figcaption');
echo '<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
	<p class="tm-figure-description">We need sanguines</p><a href="img/tm-img-16.jpg">View more</a>';
echo '</figcaption></figure></div>';


echo '</div></div></li></ul></div>';
?>
<!--<link rel="stylesheet" href="css/main_gall.css">
<div class="cd-hero">
<ul class="cd-hero-slider">
	<!-- Page 1 Gallery One 
	<li class="selected">                    
		<div class="cd-full-width">
			<div class="container-fluid js-tm-page-content" data-page-no="1" data-page-type="gallery">
				<div class="tm-img-gallery-container">
					<div class="tm-img-gallery gallery-one">
					<!-- Gallery One pop up connected with JS code below 
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-01-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">IKEA<span><strong>РАЗ</strong></span></h2>
									<p class="tm-figure-description">We need sanguines</p>
									<a href="img/tm-img-01.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-02-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">МЕГАФОН <span><strong>ДВА</strong></span></h2>
									<p class="tm-figure-description">Отними у бабушки очки </p>
									<a href="img/tm-img-02.jpg">View more</a>
								</figcaption>
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-03-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">IKEA  <span><strong>ТРИ</strong></span></h2>
									<p class="tm-figure-description">Подсаживаем на подарки.</p>
									<a href="img/tm-img-03.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-04-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">Русский  <span><strong>Стандарт</strong></span></h2>
									<p class="tm-figure-description">Неожиданно высокий процент по депозитам.</p>
									<a href="img/tm-img-04.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>  
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-05-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">Из рук <span><strong>в руки</strong></span></h2>
									<p class="tm-figure-description">Жизнь в объявлениях</p>
									<a href="img/tm-img-05.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-06-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">Билайн <span><strong>BEELINE</strong></span></h2>
									<p class="tm-figure-description">Тариф  "Добро пожаловать".</p>
									<a href="img/tm-img-06.jpg">View more</a>
								</figcaption>
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-07-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">BEELINE<span><strong>Билайн</strong></span></h2>
									<p class="tm-figure-description">Говори хоть всю дорогу</p>
									<a href="img/tm-img-07.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-08-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title"> <span><strong></strong></span></h2>
									<p class="tm-figure-description">Вот такие разговоры.</p>
									<a href="img/tm-img-08.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>   
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-09-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">ЭТОМУ<span><strong>сердцу</strong></span></h2>
									<p class="tm-figure-description"> нужно успеть достучаться до вас.</p>
									<a href="img/tm-img-09.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-10-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title"> <span><strong>DANONE</strong></span></h2>
									<p class="tm-figure-description">Доведем до ананаса .</p>
									<a href="img/tm-img-10.jpg">View more</a>
								</figcaption>
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-11-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">DANONE<span><strong></strong></span></h2>
									<p class="tm-figure-description">Новая Активия. Природа рядом!</p>
									<a href="img/tm-img-11.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-12-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">DANON<span><strong></strong></span></h2>
									<p class="tm-figure-description">Слой за слоем, в атмосферу удовольствия.</p>
									<a href="img/tm-img-12.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-13-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">DANONE<span><strong></strong></span></h2>
									<p class="tm-figure-description">Целый мир целых ягод.</p>
									<a href="img/tm-img-13.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-14-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">BEELINE <span><strong>WAP</strong></span></h2>
									<p class="tm-figure-description">История все про все.</p>
									<a href="img/tm-img-14.jpg">View more</a>
								</figcaption>
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-15-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">IKEA <span><strong></strong></span></h2>
									<p class="tm-figure-description">We need melancholics.</p>
									<a href="img/tm-img-15.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>
						<div class="grid-item">
							<figure class="effect-sadie">
								<img src="img/tm-img-16-tn.jpg" alt="Image" class="img-fluid tm-img">
								<figcaption>
									<h2 class="tm-figure-title">IKEA <span><strong></strong></span></h2>
									<p class="tm-figure-description">We need characters</p>
									<a href="img/tm-img-16.jpg">View more</a>
								</figcaption>           
							</figure>
						</div>                                                                       
					</div>                                 
				</div>
			</div>                                                    
		</div>                    
	</li>
</ul>
</div>	-->
<script src="js/jquery-1.11.3.min.js"></script>
 <script src="js/tether.min.js"></script> <!-- Tether (http://tether.io/)  --> 
        <script src="js/bootstrap.min.js"></script>             <!-- Bootstrap js (v4-alpha.getbootstrap.com/) -->
        <script src="js/hero-slider-main.js"></script>          <!-- Hero slider (https://codyhouse.co/gem/hero-slider/) -->
        <script src="js/jquery.magnific-popup.min.js"></script> <!-- Magnific 